name: 'DEPLOY API GATEWAY'
description: 'Github action for deploy to API gateway'
author: 'lampvux'
inputs:

  region: # 
    required: false
    description: 'Default AWS region'
    default: 'us-east-1'

  api_name: # 
    required: true
    description: 'API name'

  swagger_file: # 
    required: true
    description: 'Swagger API definition file'
    
  deploy_stage: # 
    required: false
    description: 'Deployment stage'
    default: 'dev'  
  api_type: # 
    required: false
    description: 'API type' 
    default: "rest"
    
outputs:
  api_uri:
    description: uri of published API
runs:
  using: 'node16'
  main: 'dist/index.js'
